name: ci

on:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ./docker.sh npm run ci:build
      - run: ./docker.sh npm test
      - uses: actions/upload-artifact@v4
        with:
          name: npm
          path: |
            ./dist/
            ./package.json
            ./README.md

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: npm
          path: npm
      - run: |
          cd npm && zip -r ../npm.zip * && cd -
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            npm.zip
      - run: |
          cd npm
          npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
